version: '2'

services:

  app:
    image: stefanwalther/circleci-angular-sentry
    container_name: app
    ports:
      - "8080:80"
    volumes:
      - app-volume:/usr/share/nginx/html

  sentry-cli:
    image: getsentry/sentry-cli
    container_name: sentry-cli
    tty: true
    depends_on:
      - app
    environment:
      - DEBUG=true
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENTRY_PROJECT_VERSION=${SENTRY_PROJECT_VERSION}
      - SENTRY_ORG=${SENTRY_ORG}
      - SENTRY_PROJECT=${SENTRY_PROJECT}
      - SENTRY_LOG_LEVEL=${SENTRY_LOG_LEVEL}
      - PROJECT_DIR=/work
    volumes:
      - app-volume/:/work
      - ./config/sentry-cli/:/work/sentry-cli/
    command: >
      sh -c "sh ./sentry-cli/sentry-cli-init.sh"

volumes:
  app-volume:
